.TH NUMBER-GAME 1 "December 2025" "number-game 1.0" "User Commands"
.SH NAME
number-game \- игра «Угадай число»
.SH SYNOPSIS
.B number-game
[\fB-r\fR] [\fB-h\fR] [\fB-V\fR]
.SH DESCRIPTION
.B number-game
загадывает целое число в диапазоне 1..100 и предлагает пользователю его отгадать.

По умолчанию используются десятичные числа.
При указании опции
.BR -r " или " --roman
игра ведётся в римской системе счисления.

Справка, выводимая программой, содержит пояснения на русском и китайском языках.
.SH OPTIONS
.TP
.BR -r ", " --roman
Запустить игру в римской системе счисления.
.TP
.BR -h ", " --help
Показать краткую справку и завершить работу.
.TP
.BR -V ", " --version
Показать информацию о версии и завершить работу.
.SH AUTHOR
Жэнь Цзежуй.
